### ISSUE TITLE
Edit groups

### ISSUE THREAD

**Issue by rayman89** [leslie-heinzen/tab-grouper#1]
I was testing your addon and think it has really cool functionality but was wondering if you were planing on allowing to eliminate tabs from groups, name the groups and add tabs to existing groups. Also would be nice to have a confirmation dialog or something similar when deleting a whole group in case is not intentional. Thank you.

**Comment by leslie-heinzen** [comment]
Thanks for using the addon, and for your feedback! I'm still early in development on this, and taking feature requests into consideration.

I like the idea of the confirmation dialog, and the ability to close individual tab group items. The other two requests change the nature of the addon a bit by giving tab groups more permanence than I had intended, but maybe long-term I will consider them. 😄 

Thanks!
Zero-man

**Comment by leslie-heinzen** [comment]
The above mentioned changes, as well as a couple of other features, are now in the stable v0.2.0 release as of #10. Closing this issue.
